name: PHP Tests

on:
  push:
    branches:
      - develop
      - main
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-tests-wp-latest-php-8-0.yml'
      - includes/**
      - tests/phpunit/**
      - /*.php
      - 'phpunit*.xml*'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-tests-wp-latest-php-8-0.yml'
      - includes/**
      - tests/phpunit/**
      - /*.php
      - 'phpunit*.xml*'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: php-tests-wp-latest-php-8-0-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-tests-wp-latest-php-8-0:
    name: PHP (PHP 8.0, WordPress Latest)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test
      WP_VERSION: latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          extensions: mysqli, runkit7, uopz
          tools: composer
          php-version: '8.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Composer Install
        run: composer install --no-interaction --no-progress
      - name: Update PHPUnit
        run: |
          composer config --unset platform.php
          composer update phpunit/phpunit --with-dependencies --no-scripts
      - name: Set up PHP test data
        run: tests/phpunit/bin/install-wp-tests.sh ${MYSQL_DATABASE} ${MYSQL_USER} ${MYSQL_PASSWORD} ${DB_HOST}:${DB_PORT} ${WP_VERSION}
      - name: Run Unit Tests
        run: composer test -- --verbose
